# Generated by Django 5.2 on 2026-06-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='guest',
            new_name='quest',
        ),
    ]
