# Generated by Django 5.2 on 2026-06-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['full_name']},
        ),
    ]
