default_context:
    student_full_name_rus: "Кочурова Вероника Владимировна"
    surname_initials_lat: "Kochurova V.V."
    db_username: "veronikakocurova"
    db_password: "14343"
    project_name_rus: "Северная пчела"
    project_name_lat: "North_bee"
    project_description: "Информационная система сети отелей"
    main_background_color: "#FFFFFF"
    aux_background_color: "#f1fe39"
    attention_color: "#3964fe"
    custom_user: "y"
    login_required: "n"
    tests_required: "n"