# Generated by Django 5.2 on 2026-06-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype_name', models.CharField(max_length=20, verbose_name='Класс номера')),
            ],
        ),
    ]
